### ISSUE TITLE
训练效果

### ISSUE THREAD

**Issue by JunnYu** [DunZhang/LUSE#1]
您好，我使用了您的代码，在roformer_chinese_char_base的12层模型基础上继续训练，lr=2.5e-5，batch_size=32继续预训练了3.5W步有如下的结果，**感觉效果没有明显提升（可能训练的步数少了,也可能是下游数据集问题）**
![image](https://user-images.githubusercontent.com/50394665/127774706-511bdbd1-03a4-488d-ab80-b1a45c61dca3.png)

**Comment by DunZhang** [comment]
> 您好，我使用了您的代码，在roformer_chinese_char_base的12层模型基础上继续训练，lr=2.5e-5，batch_size=32继续预训练了3.5W步有如下的结果，**感觉效果没有明显提升（可能训练的步数少了,也可能是下游数据集问题）**
> ![image](https://user-images.githubusercontent.com/50394665/127774706-511bdbd1-03a4-488d-ab80-b1a45c61dca3.png)

有2个可能原因:
1, 32的bsz可能还是有点小了,对比学习对bsz要求比较高
2,训练步数明显过少,我三层的模型也训练了10万步 (还是在bsz为128的情况)
应为本人无算力资源,实在没法尝试12层的模型,所以可能还要你来探索下原因吧

**Comment by JunnYu** [comment]
好的，谢谢。
（1）我这边只有一张3090，想要扩大batch可能我还需要引入一下fp16精度和梯度累计部分。
（2）到当前回复时间为止，已经训练了10W步了，我准备再让它跑个几天，看看效果。

**Comment by LMXG** [comment]
您好，我准备尝试一下您的代码，不知训练模型与文本数据集能否重新上传一下百度网盘，应该是是过期了。
